# Generated by Django 2.2.12 on 2020-05-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_shghg"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="fdsfdsfsd",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="gfjgf",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="ghfhgfh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hfjhfhgf",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hgfjgfjhfj",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homepage",
            name="hghghg",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
